services:
  # --- Nginx Proxy Manager ---
  npm:
    container_name: ${nginx_container_name}
    hostname: app2-proxy2
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'   # HTTP traffic
      - '81:81'   # NPM Admin UI
      - '443:443' # HTTPS traffic
    volumes:
      - ./nginx/npm_data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - backend
      - testnet

  # --- Vikunja Application ---
  vikunja:
    container_name: ${vik_container_name}
    image: vikunja/vikunja:2.3.0
    environment:
      VIKUNJA_MAILER_ENABLED: "true"
      VIKUNJA_MAILER_HOST: ${vik_mailer_host}
      VIKUNJA_MAILER_PORT: ${vik_mailer_port}
      VIKUNJA_MAILER_USERNAME: ${vik_mailer_username}
      VIKUNJA_MAILER_PASSWORD: ${vik_mailer_password}
      VIKUNJA_MAILER_FROMEMAIL: ${vik_mailer_fromemail}
      VIKUNJA_MAILER_FORCESSL: "false"

      VIKUNJA_SERVICE_PUBLICURL: ${vik_service_puburl}
      VIKUNJA_SERVICE_SECRET: ${vik_service_jwtsecret}
      VIKUNJA_SERVICE_ENABLEREGISTRATION: "false"

      VIKUNJA_DATABASE_HOST: ${vik_db_host}
      VIKUNJA_DATABASE_PASSWORD: ${vik_db_pw}
      VIKUNJA_DATABASE_TYPE: ${vik_db_type}
      VIKUNJA_DATABASE_USER: ${vik_db_user}
      VIKUNJA_DATABASE_DATABASE: ${vik_db_db}

      XDG_CACHE_HOME: /app/vikunja/.cache
    volumes:
      - ./vikunja/files:/app/vikunja/files
      - ./vikunja/cache:/app/vikunja/.cache
    depends_on:
      vikunja-db:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  # --- Vikunja Postgres Database ---
  vikunja-db:
    container_name: ${vikdb_container_name}
    image: postgres:18
    environment:
      POSTGRES_USER: ${vikdb_pg_user}
      POSTGRES_PASSWORD: ${vikdb_pg_pw}
      POSTGRES_DB: ${vikdb_pg_db}
    volumes:
      - ./vikunja/db:/var/lib/postgresql
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      start_period: 30s

  # --- WordPress ---
  wordpress:
    container_name: ${wp_container_name}
    image: wordpress:latest
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${wp_db_host}
      WORDPRESS_DB_USER: ${wp_db_user}
      WORDPRESS_DB_PASSWORD: ${wp_db_pw}
      WORDPRESS_DB_NAME: ${wp_db_name}
    volumes:
      - ./wordpress/data:/var/www/html
    networks:
      - backend
    depends_on:
      - wordpress-db

  # --- WordPress MySQL Database ---
  wordpress-db:
    container_name: ${wpdb_container_name}
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${wpdb_db}
      MYSQL_USER: ${wpdb_user}
      MYSQL_PASSWORD: ${wpdb_pw}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./wordpress/db:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
  testnet:
    name: test_network
    external: true
