services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    
    container_name: app1-minio1
    hostname: app1-minio1

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    
    environment:
      MINIO_ROOT_USER: ${minio_root_user}
      MINIO_ROOT_PASSWORD: ${minio_root_password}
    volumes:
      - /mnt/disk1:/data
    command: server /data --console-address ":9001"
    
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - testnet

networks:
  testnet:
    name: test_network
    external: true